require("RODBC")
dbhandle <- odbcDriverConnect(paste0('driver={SQL Server};server=',Sys.getenv("PGHOST"), ';database=',Sys.getenv("PGDATABASE"),';uid=', Sys.getenv("PGUSER"), ';pwd=', Sys.getenv("PGPASSWORD")))
res <- sqlQuery(dbhandle, 'select * from omop.person')
print(res)
write.csv(res, file='/mnt/data/average.csv', row.names=FALSE) 
