name: Build Docker Image
run-name: Building image
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build:
    uses: Aridhia-Open-Source/pipelines/.github/workflows/build-docker.yml@main
    with:
      TAG: ${{ vars.VERSION }}
      IMAGE: rtest
      BUILD_PATH: docker
      HASH_SUFFIX: false
      DOCKER_ACR: ${{ vars.DOCKER_ACR }}
    secrets:
      DOCKER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
