name: Build Docker Image
run-name: Building image
on:
  push:
    branches:
      - main
      - MS-SQL
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: Aridhia-Open-Source/pipelines/.github/workflows/build-docker.yml@main
    with:
      TAG: 1.1
      IMAGE: rtest
      BUILD_PATH: docker
      HASH_SUFFIX: false
      DOCKER_ACR: ${{ vars.DOCKER_ACR }}
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
